### ISSUE TITLE
View own content doesn't work (access denied)

### ISSUE THREAD

**Issue by marcus-leonard** [backdrop-contrib/content_access#12]
Backdrop CMS 1.23.0
Content Access 1.x-1.2.3
Devel Node Access 1.x-1.8.1

Granting "view own [content_type] content" access doesn't appear to do anything.

Steps:
1. Main permissions - "Authenticated" user has "View published content".
1. Create custom role.
1. Create a user, give them that role.
1. Install and enable Content Access module, give that role given "view own" access for a content type. (Or just give access to "Authenticated" role, makes no difference.)

A user with that role can create and edit a node but can't view that node.
- When creating a node, upon save I get bounced straight to the home page.
- Same thing if directly enter the edit URL (node/xxx/edit) and save. 
- If I try to view the node: access denied.

"view any" works as expected.

I tried debugging with Devel Node Access (DNA). With its default settings:
Block "node_access entries for nodes shown on this page" says "Content access: author of the content can access"
Block "Access permissions by user" - "view" for that user says "NO: no reason"
It's also throwing these errors:
> Notice: Undefined offset: 333 in content_access_node_access_explain() (line 625 of /srv/www/appdev1/backdrop/modules/content_access/content_access.module).
> Notice: Undefined offset: 334 in content_access_node_access_explain() (line 625 of /srv/www/appdev1/backdrop/modules/content_access/content_access.module).

With the DNA debug switched on, the node_access entries block gets more detail, still says "Content access: author of the content can access".

With the DNA setting "Asynchronously populate the Devel Node Access by User block" enabled, it gets worse. All the "Access permissions by user" links are "Error: could not explain access" and the linked report has heaps of
> Notice: Undefined offset: 2 in devel_node_access_user_ajax() (line 1021 of /srv/www/appdev1/backdrop/modules/devel/devel_node_access/devel_node_access.module).
> Notice: Undefined offset: 1 in devel_node_access_user_ajax() (line 1021 of /srv/www/appdev1/backdrop/modules/devel/devel_node_access/devel_node_access.module).
> Warning: array_flip(): Can only flip STRING and INTEGER values! in DefaultEntityController->load() (line 268 of /srv/www/appdev1/backdrop/core/modules/entity/entity.controller.inc).

Repeated lots of times, followed by
> NO: invalid $op

Content Access module page says there are 131 active installs but there are no open issues, so I figure I must be missing something, but can't work out what.

**Comment by laryn** [comment]
@marcus-leonard You are definitely turning up something with these notices and warning, so it's not just that you're missing something. I'll try to look at this when I get a chance and feel free to post further if you uncover anything more. Thanks for the report!

**Comment by laryn** [comment]
@marcus-leonard Could you test the latest dev and let me know if it works for you? It works locally for me. I had to adjust the logic slightly. Some of the adjustment that was made in the move from Drupal to Backdrop (ie. no more role IDs in the same way there were in D7) led to some logic changes that didn't properly consider the "view own" case.

**Comment by marcus-leonard** [comment]
@laryn That's done it. I installed the new code and rebuilt permissions, now it's behaving as expected. Many thanks for the quick attention. :smile: 

If I have Devel Node Access enabled, I (admin user) still get these errors:
> Notice: Undefined offset: 333 in content_access_node_access_explain() (line 636 of /path/to/backdrop/modules/content_access/content_access.module).
> Notice: Undefined offset: 334 in content_access_node_access_explain() (line 636 of /path/to/backdrop/modules/content_access/content_access.module).

And, if I enable Devel's asynchronous option, the "Access permissions by user" table displays errors (but is fine if that config is not enabled).

So is DNA exposing an issue in itself or in Content Access? If it's about DNA, I can log these errors in that issue queue.

**Comment by laryn** [comment]
@marcus-leonard 
Great, I'm glad the meat of that fix works as hoped for you.

I've just added a commit to allow fetching a role from a grant ID which should solve the warning in `hook_node_access_explain`: https://github.com/backdrop-contrib/content_access/commit/64b63490f484050e5b3a2a4dbf9f367980ec9995

Care to test that as well?

**Comment by marcus-leonard** [comment]
@laryn
Yes, it's gone, thanks again. All good from this end.

(The `devel_node_access_user_ajax()` error is still around if enabled, but I don't need it and I assume that's an issue for DNA, not here.)
